Issue#2
vitodevjav/qulix pull request #12
Opened 2017-10-19 15:31 UTC by vitodevjav

ыыыыы

2017-10-20 11:49 UTC, ghost requested changes

2017-10-20 11:49 UTC, ghost commented on testGifSearcher/ViewModels/ResultViewController.swift
> +            sleep(1)
Это что за помидор?

2017-10-20 11:49 UTC, ghost commented on testGifSearcher/ViewModels/MainViewController.swift
> +            sleep(2)
0_о

2017-10-20 11:49 UTC, ghost commented on testGifSearcher/ViewModels/MainViewController.swift
> +        tableView.isHidden = false
Где вызов метода суперкласса?

2017-10-20 12:47 UTC, ghost requested changes

2017-10-20 12:47 UTC, dzmitry-baranau commented on testGifSearcher/ViewModels/MainViewController.swift
> +        activityIndicator.isHidden = true
copy-pasted logic
should be moved into method

2017-10-20 12:47 UTC, dzmitry-baranau commented on testGifSearcher/ViewModels/MainViewController.swift
> +                refreshEnd(0)
И что значит передаваемый параметр (0)?

2017-10-20 14:19 UTC, ghost requested changes

2017-10-20 14:19 UTC, dzmitry-baranau commented on testGifSearcher/ViewModels/MainViewController.swift
> +        activityIndicator.isHidden = false
```
func myLovelyMethod(_ isHidden: Bool) {
  tableView.isHidden = !isHidden
  stateInfoView.isHidden = isHidden
  activityIndicator.isHidden = isHidden
}
```

2017-10-20 16:33 UTC, ghost requested changes

2017-10-20 16:33 UTC, dzmitry-baranau commented on testGifSearcher/ViewModels/MainViewController.swift
> +        giphyService.searchGifsByName(searchBar.text!, completion: {(isSuccess,result:[GifModel]) in
![maxresdefault](https://user-images.githubusercontent.com/5443535/31831648-dba274e2-b5cc-11e7-8d55-75b67a2477b9.jpg)

2017-10-21 18:59 UTC, ghost requested changes

2017-10-21 18:59 UTC, ghost commented on testGifSearcher/Services/GiphyService.swift
> +        for data in dataMap{
Missing space before {

2017-10-21 18:59 UTC, ghost commented on testGifSearcher/Services/GiphyService.swift
> +            }
Too many `guards`...

2017-10-21 18:59 UTC, ghost commented on testGifSearcher/Services/GiphyService.swift
> +                    completion(false,[])
Missing space after ,

2017-10-21 18:59 UTC, ghost commented on testGifSearcher/Services/GiphyService.swift
> +                }
You could just write:
`completion(!gifArray.isEmpty, gifArray)`
(as example)

2017-10-21 18:59 UTC, ghost commented on testGifSearcher/Services/GiphyService.swift
> +                    completion(false,gifArray)
It looks like copy-pasted logic (the same as in previous method)

2017-10-21 18:59 UTC, ghost commented on testGifSearcher/UIElements/CheckBox.swift
> +                self.backgroundColor = activeColor
`backgroundColor = isChecked ? passiveColor  : activeColor`

2017-10-21 18:59 UTC, ghost commented on testGifSearcher/UIElements/GifTableViewCell.swift
> +        starImageView.image = UIImage(named: "trendedImage")
Is it needed to create this image each time you use this method?

2017-10-21 18:59 UTC, dzmitry-baranau commented on testGifSearcher/ViewModels/MainViewController.swift
>      private var gifsOnScreenCount = 20;
Чем отличается от gifsCountPerRequest?

2017-10-21 18:59 UTC, dzmitry-baranau commented on testGifSearcher/ViewModels/MainViewController.swift
> +    private func beginRefresh(newtext:String, endRefresh: @escaping () -> Void) {
Даже не буду пытаться думать, что этот метод делает :-)

2017-10-21 18:59 UTC, dzmitry-baranau commented on testGifSearcher/ViewModels/ResultViewController.swift
> +//        tableView.reloadData()
Зачем комментить, когда можно удалить?

2017-10-21 18:59 UTC, dzmitry-baranau commented on testGifSearcher/ViewModels/ResultViewController.swift
> +        if (selectedGifs[indexPath.row].isTrended) {
Круглые скобки в if не нужны

2017-10-23 11:24 UTC, vitodevjav commented on testGifSearcher/Services/GiphyService.swift
> +            }
I don't now hot to change it properly

2017-10-24 10:04 UTC, ghost requested changes

2017-10-24 10:04 UTC, dzmitry-baranau commented on testGifSearcher/Services/GiphyService.swift
> +                return []
`continue`

2017-10-24 10:04 UTC, dzmitry-baranau commented on testGifSearcher/UIElements/GifTableViewCell.swift
> +        starImageView.image = trendedMarkImage
Установи картинку сразу, не делай постоянную установку.

2017-10-24 10:04 UTC, dzmitry-baranau commented on testGifSearcher/ViewModels/MainViewController.swift
> +    private func loadMoreGifs(completion: @escaping ()->Void) {
?

2017-10-24 10:04 UTC, dzmitry-baranau commented on testGifSearcher/ViewModels/MainViewController.swift
> +        DispatchQueue.main.async {
С чего взял, что не на мейне метод вызывается?

2017-10-24 13:27 UTC, ghost approved these changes

2017-10-24 13:27 UTC, merged